using XGBoost.Demos.Common;

namespace XGBoost.Demos.GuidePython;

/// <summary>
/// Gamma regression. Port of <c>demo/guide-python/gamma_regression.py</c>.
/// </summary>
/// <remarks>
/// Fits a gamma regression model (with log link function). The Python demo reads
/// <c>demo/data/autoclaims.csv</c>, generated by running <c>gen_autoclaims.R</c> in that folder. When the
/// file is missing, synthetic gamma-distributed claims of the same shape are used instead.
/// </remarks>
internal static class GammaRegression
{
    public static void Run(string[] args)
    {
        var data = LoadAutoclaims();
        var features = Enumerable.Range(0, 34).ToArray();
        var train = Enumerable.Range(0, 4741).ToArray();
        var test = Enumerable.Range(4741, 6773 - 4741).ToArray();
        var label = data.Column(34);
        using var dtrain = data.TakeRows(train).TakeColumns(features).ToDMatrix(label.Gather(train));
        using var dtest = data.TakeRows(test).TakeColumns(features).ToDMatrix(label.Gather(test));

        // for gamma regression, we need to set the objective to 'reg:gamma', it also suggests to set the
        // base_score to a value between 1 to 5 if the number of iteration is small
        var param = P.Of(("objective", "reg:gamma"), ("booster", "gbtree"), ("base_score", 3));

        // the rest of settings are the same
        (DMatrix, string)[] watchlist = [(dtest, "eval"), (dtrain, "train")];
        const int numRound = 30;

        // training and evaluation
        using var bst = XGB.Train(param, dtrain, numRound, watchlist,
            onIteration: (i, results) => Console.WriteLine(Training.FormatLine(i, results)));
        var preds = bst.Predict(dtest).Values;
        var labels = dtest.Label;
        var deviance = 2 * labels.Select((l, i) => (l - preds[i]) / preds[i] - Math.Log(l) + Math.Log(preds[i])).Sum();
        Console.WriteLine($"test deviance={deviance:F6}");
    }

    private static DenseData LoadAutoclaims()
    {
        var path = DemoPaths.Data("autoclaims.csv");
        if (File.Exists(path)) return Datasets.LoadCsv(path, hasHeader: false).Data;

        Console.WriteLine($"{path} not found (run demo/data/gen_autoclaims.R to create it); using synthetic claims.");
        // 34 binary/continuous rating factors and a positive claim amount whose mean depends on a few of them.
        var rng = new Rng(0);
        var data = DenseData.Zeros(6773, 35);
        for (var r = 0; r < data.Rows; r++)
        {
            for (var c = 0; c < 34; c++) data[r, c] = c < 10 ? (float)rng.Normal() : rng.Integers(0, 2);
            var logMean = 1.2 + 0.3 * data[r, 0] - 0.2 * data[r, 1] + 0.4 * data[r, 10] - 0.3 * data[r, 11];
            const double shape = 2;
            data[r, 34] = (float)rng.Gamma(shape, Math.Exp(logMean) / shape);
        }
        return data;
    }
}
